# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import core.grpc.syncindex_pb2 as syncindex__pb2


class SyncIndexStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Reindex = channel.unary_unary(
            '/syncindex.SyncIndex/Reindex',
            request_serializer=syncindex__pb2.SyncRequest.SerializeToString,
            response_deserializer=syncindex__pb2.SyncReply.FromString,
        )
        self.Add = channel.unary_unary(
            '/syncindex.SyncIndex/Add',
            request_serializer=syncindex__pb2.SyncRequest.SerializeToString,
            response_deserializer=syncindex__pb2.SyncReply.FromString,
        )
        self.Delete = channel.unary_unary(
            '/syncindex.SyncIndex/Delete',
            request_serializer=syncindex__pb2.SyncRequest.SerializeToString,
            response_deserializer=syncindex__pb2.SyncReply.FromString,
        )
        self.Search = channel.unary_unary(
            '/syncindex.SyncIndex/Search',
            request_serializer=syncindex__pb2.SyncRequest.SerializeToString,
            response_deserializer=syncindex__pb2.SyncReply.FromString,
        )
        self.Meta = channel.unary_unary(
            '/syncindex.SyncIndex/Meta',
            request_serializer=syncindex__pb2.SyncRequest.SerializeToString,
            response_deserializer=syncindex__pb2.SyncReply.FromString,
        )
        self.Greeting = channel.unary_unary(
            '/syncindex.SyncIndex/Greeting',
            request_serializer=syncindex__pb2.SyncRequest.SerializeToString,
            response_deserializer=syncindex__pb2.SyncReply.FromString,
        )


class SyncIndexServicer(object):
    """The greeting service definition.
    """

    def Reindex(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Meta(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Greeting(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncIndexServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Reindex': grpc.unary_unary_rpc_method_handler(
            servicer.Reindex,
            request_deserializer=syncindex__pb2.SyncRequest.FromString,
            response_serializer=syncindex__pb2.SyncReply.SerializeToString,
        ),
        'Add': grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=syncindex__pb2.SyncRequest.FromString,
            response_serializer=syncindex__pb2.SyncReply.SerializeToString,
        ),
        'Delete': grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=syncindex__pb2.SyncRequest.FromString,
            response_serializer=syncindex__pb2.SyncReply.SerializeToString,
        ),
        'Search': grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=syncindex__pb2.SyncRequest.FromString,
            response_serializer=syncindex__pb2.SyncReply.SerializeToString,
        ),
        'Meta': grpc.unary_unary_rpc_method_handler(
            servicer.Meta,
            request_deserializer=syncindex__pb2.SyncRequest.FromString,
            response_serializer=syncindex__pb2.SyncReply.SerializeToString,
        ),
        'Greeting': grpc.unary_unary_rpc_method_handler(
            servicer.Greeting,
            request_deserializer=syncindex__pb2.SyncRequest.FromString,
            response_serializer=syncindex__pb2.SyncReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'syncindex.SyncIndex', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
