# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncindex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='syncindex.proto',
  package='syncindex',
  syntax='proto3',
  serialized_options=_b('\n\"com.bdatacap.faiss.syncindexB\016SyncIndexProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0fsyncindex.proto\x12\tsyncindex\"^\n\x0bSyncRequest\x12\x0c\n\x04rcId\x18\x01 \x01(\t\x12\x0b\n\x03ids\x18\x02 \x03(\t\x12\t\n\x01k\x18\x03 \x01(\x05\x12)\n\x07vectors\x18\x04 \x03(\x0b\x32\x18.syncindex.InternalArray\"\x1f\n\rInternalArray\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"8\n\tSyncReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\xe5\x02\n\tSyncIndex\x12\x39\n\x07Reindex\x12\x16.syncindex.SyncRequest\x1a\x14.syncindex.SyncReply\"\x00\x12\x35\n\x03\x41\x64\x64\x12\x16.syncindex.SyncRequest\x1a\x14.syncindex.SyncReply\"\x00\x12\x38\n\x06\x44\x65lete\x12\x16.syncindex.SyncRequest\x1a\x14.syncindex.SyncReply\"\x00\x12\x38\n\x06Search\x12\x16.syncindex.SyncRequest\x1a\x14.syncindex.SyncReply\"\x00\x12\x36\n\x04Meta\x12\x16.syncindex.SyncRequest\x1a\x14.syncindex.SyncReply\"\x00\x12:\n\x08Greeting\x12\x16.syncindex.SyncRequest\x1a\x14.syncindex.SyncReply\"\x00\x42<\n\"com.bdatacap.faiss.syncindexB\x0eSyncIndexProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_SYNCREQUEST = _descriptor.Descriptor(
  name='SyncRequest',
  full_name='syncindex.SyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rcId', full_name='syncindex.SyncRequest.rcId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ids', full_name='syncindex.SyncRequest.ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='syncindex.SyncRequest.k', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vectors', full_name='syncindex.SyncRequest.vectors', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=124,
)


_INTERNALARRAY = _descriptor.Descriptor(
  name='InternalArray',
  full_name='syncindex.InternalArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='syncindex.InternalArray.vector', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=157,
)


_SYNCREPLY = _descriptor.Descriptor(
  name='SyncReply',
  full_name='syncindex.SyncReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='syncindex.SyncReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='syncindex.SyncReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='syncindex.SyncReply.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=215,
)

_SYNCREQUEST.fields_by_name['vectors'].message_type = _INTERNALARRAY
DESCRIPTOR.message_types_by_name['SyncRequest'] = _SYNCREQUEST
DESCRIPTOR.message_types_by_name['InternalArray'] = _INTERNALARRAY
DESCRIPTOR.message_types_by_name['SyncReply'] = _SYNCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SyncRequest = _reflection.GeneratedProtocolMessageType('SyncRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYNCREQUEST,
  __module__ = 'syncindex_pb2'
  # @@protoc_insertion_point(class_scope:syncindex.SyncRequest)
  ))
_sym_db.RegisterMessage(SyncRequest)

InternalArray = _reflection.GeneratedProtocolMessageType('InternalArray', (_message.Message,), dict(
  DESCRIPTOR = _INTERNALARRAY,
  __module__ = 'syncindex_pb2'
  # @@protoc_insertion_point(class_scope:syncindex.InternalArray)
  ))
_sym_db.RegisterMessage(InternalArray)

SyncReply = _reflection.GeneratedProtocolMessageType('SyncReply', (_message.Message,), dict(
  DESCRIPTOR = _SYNCREPLY,
  __module__ = 'syncindex_pb2'
  # @@protoc_insertion_point(class_scope:syncindex.SyncReply)
  ))
_sym_db.RegisterMessage(SyncReply)


DESCRIPTOR._options = None

_SYNCINDEX = _descriptor.ServiceDescriptor(
  name='SyncIndex',
  full_name='syncindex.SyncIndex',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=218,
  serialized_end=575,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reindex',
    full_name='syncindex.SyncIndex.Reindex',
    index=0,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='syncindex.SyncIndex.Add',
    index=1,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='syncindex.SyncIndex.Delete',
    index=2,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='syncindex.SyncIndex.Search',
    index=3,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Meta',
    full_name='syncindex.SyncIndex.Meta',
    index=4,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Greeting',
    full_name='syncindex.SyncIndex.Greeting',
    index=5,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYNCINDEX)

DESCRIPTOR.services_by_name['SyncIndex'] = _SYNCINDEX

# @@protoc_insertion_point(module_scope)
